# This is a GitHub workflow defining a set of jobs with a set of steps.
# ref: https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions
#
name: Test

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  pytest:
    name: "Run tests"
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - python-version: 3.7
            jupyterhub-version: 1.*
          - python-version: 3.8
            jupyterhub-version: 2.0.*
          - python-version: 3.9
            jupyterhub-version: 2.*

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "${{ matrix.python-version}}"

      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: "16"

      - name: Install configurable-http-proxy
        run: |
          npm install -g configurable-http-proxy

      - name: Install Python dependencies
        run: |
          pip install -e . -r dev-requirements.txt

      - name: Install specified jupyterhub version
        if: ${{ matrix.jupyterhub-version }}
        run: |
          pip install --pre jupyterhub==${{ matrix.jupyterhub-version }}

      - name: Show environment
        run: |
          pip freeze

      - name: Run tests
        continue-on-error: ${{ matrix.accept-failure == true }}
        run: |
          pytest -v --maxfail=2 --color=yes --cov jupyterhub_idle_culler

      - name: Publish coverage
        run: |
          codecov
